#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2018-12-05 17:28:57
# Project: shici

from pyspider.libs.base_handler import *
import time

class Handler(BaseHandler):
    crawl_config = {
    }

    @every(minutes=24 * 60)
    def on_start(self):
        self.crawl('http://www.shicimingju.com/category/all__1', callback=self.index_page)

    @config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('.www-main-container > h3 > a').items():
            self.crawl(each.attr.href, callback=self.detail_page)
        #time.sleep(3)
        next = response.doc('.pagination.www-shadow-card > a:last-child').attr.href
        self.crawl(next,callback = self.index_page)
    @config(priority=2)
    def detail_page(self, response):
        return {
            "url": response.url,
            "title": response.doc('title').text(),
            "作者名字": response.doc('.zuozhe-header.www-shadow-card > h2 > a').text(),
            "朝代": response.doc('.zuozhe-header.www-shadow-card > div:nth-child(3)').text().split('：')[-1],
            "作者作品数量": response.doc('.zuozhe-header.www-shadow-card > div:nth-child(4)').text().split('：')[-1].split('首')[0],
            "作者简介": response.doc('.summary').text(),
        }
